"""Incident 顶层失败原因（failure_code）词表（V1.5，六码锁定）。

语义见 docs/design.md 第 41 章：
- NO_SUBMISSION / MISSING_EVIDENCE / LOW_CONFIDENCE → INSUFFICIENT_EVIDENCE
- LLM_ERROR / TOOL_ERROR / MAX_STEPS → ESCALATED
TOOL_ERROR 为契约预留（V1 工具失败走 ToolResult(success=False)，不主动触发）。
"""
NO_SUBMISSION = "NO_SUBMISSION"
MISSING_EVIDENCE = "MISSING_EVIDENCE"
LOW_CONFIDENCE = "LOW_CONFIDENCE"
LLM_ERROR = "LLM_ERROR"
TOOL_ERROR = "TOOL_ERROR"
MAX_STEPS = "MAX_STEPS"
